# Generated by Django 5.1.4 on 2025-06-20 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor(es)')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='biblioteca/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'mp3'])], verbose_name='Archivo')),
                ('tipo', models.CharField(blank=True, choices=[('LIB', 'Libro'), ('ART', 'Artículo'), ('TES', 'Tesis'), ('DOC', 'Documento'), ('VID', 'Video'), ('IMG', 'Imagen'), ('AUD', 'Audio'), ('OTR', 'Otro')], max_length=3, verbose_name='Tipo')),
                ('area', models.CharField(blank=True, choices=[('HIS', 'Historia'), ('TEC', 'Técnica'), ('RES', 'Restauración'), ('ART', 'Artístico'), ('ARQ', 'Arquitectónico'), ('SOC', 'Social'), ('CUL', 'Cultural')], max_length=3, verbose_name='Área temática')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('vista_previa', models.ImageField(blank=True, null=True, upload_to='biblioteca/previews/', verbose_name='Vista previa')),
            ],
            options={
                'verbose_name': 'Recurso bibliográfico',
                'verbose_name_plural': 'Recursos bibliográficos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='imagen_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='client/static/img/catalogo', verbose_name='Imagen detalle'),
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='imagen_principal',
            field=models.ImageField(blank=True, default='', upload_to='client/static/img/catalogo', verbose_name='Imagen principal'),
        ),
    ]
