# Generated by Django 5.1.4 on 2025-06-18 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azulejo',
            options={'verbose_name': 'Ubicación de Azulejo', 'verbose_name_plural': 'Ubicaciones de Azulejos'},
        ),
        migrations.AddField(
            model_name='azulejo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
