# Generated by Django 5.1.4 on 2025-06-20 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_recursobibliografico_alter_azulejo_imagen_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('rol', models.CharField(choices=[('INV', 'Investigador'), ('ARQ', 'Arquitecto'), ('HIS', 'Historiador'), ('DES', 'Diseñador'), ('DEV', 'Desarrollador'), ('FOT', 'Fotógrafo'), ('ADM', 'Administrador'), ('COL', 'Colaborador')], max_length=3, verbose_name='Rol principal')),
                ('rol_secundario', models.CharField(blank=True, choices=[('INV', 'Investigador'), ('ARQ', 'Arquitecto'), ('HIS', 'Historiador'), ('DES', 'Diseñador'), ('DEV', 'Desarrollador'), ('FOT', 'Fotógrafo'), ('ADM', 'Administrador'), ('COL', 'Colaborador')], max_length=3, null=True, verbose_name='Rol secundario')),
                ('biografia', models.TextField(verbose_name='Biografía profesional')),
                ('imagen', models.ImageField(upload_to='equipo/', verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter (X)')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp (número)')),
                ('discord', models.CharField(blank=True, max_length=50, verbose_name='Discord (usuario)')),
                ('especializacion', models.CharField(max_length=100, verbose_name='Especialización')),
                ('citacion_favorita', models.TextField(blank=True, verbose_name='Citación favorita')),
                ('proyectos_destacados', models.TextField(blank=True, verbose_name='Proyectos destacados')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='recursobibliografico',
            name='archivo',
            field=models.FileField(upload_to='client/static/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'mp3'])], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='recursobibliografico',
            name='vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='client/static/documents/previews/', verbose_name='Vista previa'),
        ),
    ]
