# Generated by Django 5.1.4 on 2025-06-19 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_azulejo_options_azulejo_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('autor', models.CharField(default='Equipo Editorial', max_length=100, verbose_name='Autor')),
                ('destacada', models.BooleanField(default=False, verbose_name='Noticia destacada')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='client/static/img/azulejos'),
        ),
    ]
