# Generated by Django 5.1.4 on 2025-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_noticia_alter_azulejo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAzulejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estilo', models.CharField(choices=[('COL', 'Colonial'), ('BAR', 'Barroco'), ('NEO', 'Neoclásico'), ('ART', 'Art Nouveau'), ('DEC', 'Art Déco'), ('MOD', 'Moderno'), ('CON', 'Contemporáneo')], max_length=3, verbose_name='Estilo')),
                ('epoca', models.CharField(max_length=50, verbose_name='Época')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('imagen_principal', models.ImageField(upload_to='catalogo/', verbose_name='Imagen principal')),
                ('imagen_detalle', models.ImageField(blank=True, null=True, upload_to='catalogo/', verbose_name='Imagen detalle')),
                ('fecha_documentacion', models.DateField(verbose_name='Fecha de documentación')),
                ('coleccion', models.CharField(blank=True, max_length=100, verbose_name='Colección')),
                ('patron', models.BooleanField(default=False, verbose_name='Tiene patrón repetitivo')),
                ('color_principal', models.CharField(max_length=50, verbose_name='Color principal')),
            ],
            options={
                'verbose_name': 'Azulejo catalogado',
                'verbose_name_plural': 'Azulejos catalogados',
                'ordering': ['epoca', 'estilo'],
            },
        ),
    ]
