# Generated by Django 5.1.4 on 2025-06-23 06:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_miembroequipo_alter_recursobibliografico_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroequipo',
            name='imagen',
            field=models.ImageField(upload_to='client/static/img/equipo/', verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='CuentoAnimado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('contenido', models.TextField(verbose_name='Contenido del cuento (HTML)')),
                ('portada', models.ImageField(upload_to='cuentos/portadas/', verbose_name='Portada')),
                ('archivo_animado', models.FileField(upload_to='cuentos/animaciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'gif'])], verbose_name='Archivo animado')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (segundos)')),
                ('nivel', models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1, verbose_name='Nivel')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('personaje_principal', models.CharField(choices=[('AZU', 'Azulejín'), ('AZA', 'Azulejina')], default='AZU', max_length=20, verbose_name='Personaje principal')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='cuentos_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuento animado',
                'verbose_name_plural': 'Cuentos animados',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
