# Generated by Django 5.1.4 on 2025-06-23 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_miembroequipo_imagen_cuentoanimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerCreativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen_portada', models.ImageField(upload_to='talleres/portadas/', verbose_name='Imagen de portada')),
                ('video_tutorial', models.FileField(blank=True, null=True, upload_to='talleres/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])], verbose_name='Video tutorial')),
                ('duracion_estimada', models.PositiveIntegerField(verbose_name='Duración estimada (min)')),
                ('nivel_dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Medio'), ('D', 'Difícil')], max_length=1, verbose_name='Nivel de dificultad')),
                ('tipo_taller', models.CharField(choices=[('VIR', 'Virtual'), ('PRE', 'Presencial'), ('HIB', 'Híbrido')], max_length=3, verbose_name='Tipo de taller')),
                ('materiales_necesarios', models.TextField(verbose_name='Materiales necesarios')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('edad_recomendada_min', models.PositiveIntegerField(default=6, verbose_name='Edad mínima recomendada')),
                ('edad_recomendada_max', models.PositiveIntegerField(default=12, verbose_name='Edad máxima recomendada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('personaje_principal', models.CharField(choices=[('AZU', 'Azulejín'), ('AZA', 'Azulejina')], default='AZU', max_length=3, verbose_name='Personaje principal')),
            ],
            options={
                'verbose_name': 'Taller creativo',
                'verbose_name_plural': 'Talleres creativos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AlterField(
            model_name='cuentoanimado',
            name='archivo_animado',
            field=models.FileField(upload_to='client/static/cuentos/animaciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'gif'])], verbose_name='Archivo animado'),
        ),
        migrations.AlterField(
            model_name='cuentoanimado',
            name='portada',
            field=models.ImageField(upload_to='client/static/cuentos/portadas/', verbose_name='Portada'),
        ),
    ]
