# Generated by Django 5.1.4 on 2025-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_catalogoazulejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='azulejo',
            name='coleccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colección'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='epoca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Época'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='estilo',
            field=models.CharField(blank=True, choices=[('COL', 'Colonial'), ('BAR', 'Barroco'), ('NEO', 'Neoclásico'), ('ART', 'Art Nouveau'), ('DEC', 'Art Déco'), ('MOD', 'Moderno'), ('CON', 'Contemporáneo')], default='', max_length=3, verbose_name='Estilo'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='fecha_documentacion',
            field=models.DateField(blank=True, default='', verbose_name='Fecha de documentación'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='imagen_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/', verbose_name='Imagen detalle'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='imagen_principal',
            field=models.ImageField(blank=True, default='', upload_to='catalogo/', verbose_name='Imagen principal'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='azulejo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='azulejo',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='catalogoazulejo',
            name='imagen_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='client/static/img/catalogo', verbose_name='Imagen detalle'),
        ),
        migrations.AlterField(
            model_name='catalogoazulejo',
            name='imagen_principal',
            field=models.ImageField(upload_to='client/static/img/catalogo', verbose_name='Imagen principal'),
        ),
    ]
