# Generated by Django 5.1.4 on 2025-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_azulejo_coleccion_azulejo_epoca_azulejo_estilo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azulejo',
            name='fecha_documentacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de documentación'),
        ),
    ]
