# Generated by Django 5.1.4 on 2025-06-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_azulejo_fecha_documentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azulejo',
            name='fecha_documentacion',
        ),
    ]
