# Generated by Django 5.1.4 on 2025-06-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_delete_catalogoazulejo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
